apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  GREETINGS: ALOHA
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  DATABASE_URI: cG9zdGdyZXNxbCtwc3ljb3BnMjovL215dXNlcjpwYXNzd2RAcG9zdGdyZXM6NTQzMi9teWFwcAo=
