apiVersion: v1
kind: ConfigMap
metadata:
  name: myhelmapp-config
data:
  GREETINGS: ALOHA
---
apiVersion: v1
kind: Secret
metadata:
  name: myhelmapp-secret
type: Opaque
data:
  DATABASE_URI: {{ printf "postgresql+psycopg2://%s:%s@%s:%s/%s" .Values.externalPostgresql.postgresqlUsername .Values.externalPostgresql.postgresqlPassword .Values.externalPostgresql.postgresqlDatabase .Values.externalPostgresql.postgresqlHost .Values.externalPostgresql.postgresqlPort | b64enc | quote }}
